"""create sender_allowlist and sender_blocklist tables

Revision ID: f11c1892443a
Revises: 
Create Date: 2026-06-12 20:29:44.947565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11c1892443a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sender_allowlist',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('sender_email', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sender_allowlist_domain', 'sender_allowlist', ['domain'])
    op.create_table('sender_blocklist',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('pattern', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("category IN ('financial', 'promotional')", name='ck_sender_blocklist_category'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sender_blocklist_domain', 'sender_blocklist', ['domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sender_blocklist_domain', table_name='sender_blocklist')
    op.drop_table('sender_blocklist')
    op.drop_index('ix_sender_allowlist_domain', table_name='sender_allowlist')
    op.drop_table('sender_allowlist')
    # ### end Alembic commands ###
