"""add users.last_seen_at (dormant-account auto-sync skip)

The hourly auto-sync tick looped EVERY non-deleted user, so an account that
signed up once and never came back kept costing Claude calls every hour,
indefinitely — a cost that scales with churn rather than usage.

NOT NULL with server_default now(): existing rows backfill to "seen at
deploy" (they are current testers, not dormant), and new rows are eligible
for their first sync immediately. Written by hand rather than autogenerated —
autogenerate proposes dropping ix_sender_allowlist_domain /
ix_sender_blocklist_domain, a known false diff documented in ea23631396aa.

Revision ID: a8f1c2d43e70
Revises: 7b454f8c8a6d
"""

import sqlalchemy as sa
from alembic import op

revision = "a8f1c2d43e70"
down_revision = "7b454f8c8a6d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )


def downgrade() -> None:
    op.drop_column("users", "last_seen_at")
